-- TestLink v0.1 — ClickHouse DDL (reference; applied by Go on startup)
CREATE DATABASE IF NOT EXISTS testlink;

CREATE TABLE IF NOT EXISTS testlink.tl_target (
    id              UInt64,
    name            String,
    group_name      String,
    role            String,
    url             String,
    method          String DEFAULT 'GET',
    mode            String DEFAULT 'no-cors',
    timeout_ms      UInt32 DEFAULT 5000,
    repeat_count    UInt8 DEFAULT 4,
    cache_bust      UInt8 DEFAULT 0,
    latency_warn_ms UInt32 DEFAULT 0,
    extract_rule    String DEFAULT '',
    player_visible  UInt8 DEFAULT 1,
    display_order   UInt32 DEFAULT 0,
    enabled         UInt8 DEFAULT 1,
    note            String DEFAULT '',
    updated_at      DateTime DEFAULT now(),
    version         UInt64
) ENGINE = ReplacingMergeTree(version) ORDER BY id;

CREATE TABLE IF NOT EXISTS testlink.tl_session (
    session_id      String,
    created_at      DateTime DEFAULT now(),
    player_ip       String,
    country         String DEFAULT '',
    province        String DEFAULT '',
    city            String DEFAULT '',
    isp             String DEFAULT '',
    asn             String DEFAULT '',
    ua              String DEFAULT '',
    browser         String DEFAULT '',
    os              String DEFAULT '',
    net_type        String DEFAULT '',
    net_downlink    String DEFAULT '',
    game            String DEFAULT '',
    server          String DEFAULT '',
    ticket          String DEFAULT '',
    symptom         String DEFAULT '',
    note            String DEFAULT '',
    verdict         String DEFAULT '',
    verdict_detail  String DEFAULT '',
    config_snapshot String DEFAULT '',
    version         UInt64
) ENGINE = ReplacingMergeTree(version) ORDER BY session_id;

CREATE TABLE IF NOT EXISTS testlink.tl_probe_result (
    session_id      String,
    target_id       UInt64,
    target_name     String,
    group_name      String,
    role            String,
    url             String,
    host            String DEFAULT '',
    port            UInt16 DEFAULT 443,
    attempt_no      UInt8,
    outcome         String,
    http_status     Nullable(UInt16),
    total_ms        UInt16 DEFAULT 0,
    cold_ms         Nullable(UInt16),
    dns_ms          Nullable(UInt16),
    tcp_ms          Nullable(UInt16),
    tls_ms          Nullable(UInt16),
    ttfb_ms         Nullable(UInt16),
    resolved_ip     Nullable(String),
    resp_headers    String DEFAULT '',
    resp_body       String DEFAULT '',
    resolved_geo    Nullable(String),
    error           String DEFAULT '',
    created_at      DateTime DEFAULT now(),
    player_ip       String,
    country         String DEFAULT '',
    province        String DEFAULT '',
    city            String DEFAULT '',
    isp             String DEFAULT '',
    asn             String DEFAULT '',
    game            String DEFAULT '',
    server          String DEFAULT ''
) ENGINE = ReplacingMergeTree(created_at) ORDER BY (session_id, target_id, attempt_no);
